<?php
require_once '../../conexion.php';
require_once 'fpdf/fpdf.php';
$pdf = new FPDF('P', 'mm', 'Letter');
$pdf->AddPage();
$pdf->SetMargins(5, 0, 0);
$pdf->SetTitle("Salida");
$pdf->SetFont('Arial', 'B', 12);
$id = $_GET['v'];
$idcliente = $_GET['cl'];
$config = mysqli_query($conexion, "SELECT * FROM configuracion");
$datos = mysqli_fetch_assoc($config);
$clientes = mysqli_query($conexion, "SELECT * FROM cliente WHERE idcliente = $idcliente");
$datosC = mysqli_fetch_assoc($clientes);
$ventas = mysqli_query($conexion, "SELECT d.*, s.idservicios, s.descripcion,s.especialidad FROM detalle_ventas d INNER JOIN servicios s ON d.id_servicios = s.idservicios WHERE d.id_venta = $id");
$pdf->Cell(160, 17, utf8_decode($datos['nombre']), 0, 1, 'C');
$pdf->image("../../assets/img/logito.png", 150, 10, 60, 30, 'PNG');
$pdf->image("../../assets/img/qr-code.png", 30, 200, 30, 20, 'PNG');
$pdf->SetFont('Arial', 'B', 9);
$pdf->Cell(17, 5, utf8_decode("Teléfono: "), 0, 0, 'L');
$pdf->SetFont('Arial', '', 9);
$pdf->Cell(17, 5, $datos['telefono'], 0, 1, 'L');
$pdf->SetFont('Arial', 'B', 9);
$pdf->Cell(17, 5, utf8_decode("Dirección: "), 0, 0, 'L');
$pdf->SetFont('Arial', '', 9);
$pdf->Cell(17, 5, utf8_decode($datos['direccion']), 0, 1, 'L');
$pdf->SetFont('Arial', 'B', 9);
$pdf->Cell(17, 5, "Correo: ", 0, 0, 'L');
$pdf->SetFont('Arial', '', 9);
$pdf->Cell(17, 5, utf8_decode($datos['email']), 0, 1, 'L');
$pdf->Ln();
$pdf->SetFont('Arial', 'B', 8);
$pdf->SetFillColor(0, 0, 0);
$pdf->SetTextColor(255, 255, 255);
$pdf->Cell(200, 5, "Datos del cliente", 1, 1, 'C', 1);
$pdf->SetTextColor(0, 0, 0);
$pdf->Cell(40, 5, utf8_decode('Nombre'), 0, 0, 'L');
$pdf->Cell(40, 5, utf8_decode('Apellido'), 0, 0, 'L');
$pdf->Cell(40, 5, utf8_decode('Cedula'), 0, 0, 'L');
$pdf->Cell(40, 5, utf8_decode('Teléfono'), 0, 0, 'L');
$pdf->Cell(40, 5, utf8_decode('Dirección'), 0, 1, 'L');
$pdf->SetFont('Arial', '', 7);
$pdf->Cell(40, 5, utf8_decode($datosC['nombre']), 0, 0, 'L');
$pdf->Cell(40, 5, utf8_decode($datosC['apellido']), 0, 0, 'L');
$pdf->Cell(40, 5, utf8_decode($datosC['cedula']), 0, 0, 'L');
$pdf->Cell(40, 5, utf8_decode($datosC['telefono']), 0, 0, 'L');
$pdf->Cell(40, 5, utf8_decode($datosC['direccion']), 0, 1, 'L');
$pdf->Ln(3);
$pdf->SetFont('Arial', 'B', 8);
$pdf->SetTextColor(255, 255, 255);
$pdf->Cell(200, 5, "Detalle de Producto", 1, 1, 'C', 1);
$pdf->SetTextColor(0, 0, 0);
$pdf->Cell(40, 5, utf8_decode('Descripción'), 0, 0, 'L');
$pdf->Cell(40, 5, utf8_decode('Especialidad'), 0, 0, 'L');
$pdf->Cell(40, 5, 'Cantidad', 0, 0, 'C');
$pdf->Cell(40, 5, 'Precio ($)', 0, 0, 'C');
$pdf->Cell(40, 5, 'Sub Total(BS).', 0, 1, 'L');
$pdf->SetFont('Arial', '', 7);
$totalbs = 0.00;
$total = 0.00;
$desc = 0.00;
while ($row = mysqli_fetch_assoc($ventas)) {
    $pdf->Cell(40, 5, $row['descripcion'], 0, 0, 'L');
    $pdf->Cell(40, 5, $row['especialidad'], 0, 0, 'L');
    $pdf->Cell(40, 5, $row['cantidad'], 0, 0, 'C');
    $pdf->Cell(40, 5, $row['precio'], 0, 0, 'C');
    $sub_total = $row['total'];
    $sub_totalbs = $row['totalbs'];
    $total = $total + $sub_total;
    $totalbs = $totalbs + $sub_totalbs;
    $desc = $desc + $row['descuento'];
    $pdf->Cell(15, 5, number_format($sub_totalbs, 2, '.', ','), 0, 1, 'L');
  
}
$pdf->Ln(50);
$pdf->SetFont('Arial', 'B', 12);
$pdf->Cell(200, 5, 'Descuento Total', 0, 1, 'R');
$pdf->SetFont('Arial', '', 12);
$pdf->Cell(200, 5, number_format($desc, 2, '.', ','), 0, 1, 'R');
$pdf->SetFont('Arial', 'B', 12);
$pdf->Cell(200, 5, 'Total $', 0, 1, 'R');
$pdf->SetFont('Arial', '', 12);
$pdf->Cell(200, 5, number_format($total, 2, '.', ','), 0, 1, 'R');
$pdf->SetFont('Arial', 'B', 12);
$pdf->Cell(200, 5, 'Total BS', 0, 1, 'R');
$pdf->SetFont('Arial', '', 12);
$pdf->Cell(200, 5, number_format($totalbs, 2, '.', ','), 0, 1, 'R');

$pdf->Output("Factura.pdf", "I");

?>